name = "boko-influencer"
client_id = "b29da7584f3fca0a2dc40d1b48af06ba"
application_url = "https://boko-influencer.replit.app"
embedded = true

[access_scopes]
scopes = "read_orders,read_customers,read_discounts,write_discounts,read_products"

[auth]
redirect_urls = [
  "https://boko-influencer.replit.app/auth/callback",
  "https://boko-influencer.replit.app/auth/shopify/callback"
]

[webhooks]
api_version = "2024-10"

  [[webhooks.subscriptions]]
  topics = ["orders/create"]
  uri = "/webhooks/orders.create"

  [[webhooks.subscriptions]]
  topics = ["orders/cancelled"]
  uri = "/webhooks/orders.cancelled"

  [[webhooks.subscriptions]]
  topics = ["app/uninstalled"]
  uri = "/webhooks/app.uninstalled"

[app_proxy]
url = "https://boko-influencer.replit.app/proxy"
subpath = "boko-influencer"
prefix = "apps"

[build]
automatically_update_urls_on_dev = false
