name = "boko-influencer"
client_id = "b29da7584f3fca0a2dc40d1b48af06ba"
application_url = "https://35daa581-0fa6-4815-8bb3-b5c70367c082-00-35fajdw2tvw2d.sisko.replit.dev"
embedded = true

[access_scopes]
scopes = "read_orders,read_customers,read_discounts,write_discounts,read_products"

[auth]
redirect_urls = [
  "https://35daa581-0fa6-4815-8bb3-b5c70367c082-00-35fajdw2tvw2d.sisko.replit.dev/auth/callback",
  "https://35daa581-0fa6-4815-8bb3-b5c70367c082-00-35fajdw2tvw2d.sisko.replit.dev/auth/shopify/callback"
]

[webhooks]
api_version = "2024-10"

  [[webhooks.subscriptions]]
  topics = ["orders/create"]
  uri = "/webhooks/orders.create"

  [[webhooks.subscriptions]]
  topics = ["orders/cancelled"]
  uri = "/webhooks/orders.cancelled"

  [[webhooks.subscriptions]]
  topics = ["app/uninstalled"]
  uri = "/webhooks/app.uninstalled"

[app_proxy]
url = "https://35daa581-0fa6-4815-8bb3-b5c70367c082-00-35fajdw2tvw2d.sisko.replit.dev/proxy"
subpath = "boko-influencer"
prefix = "apps"

[build]
automatically_update_urls_on_dev = true
